gfcli:
  gen:
    dao:
    - link:     "mysql:root:root@tcp(192.168.1.4:3306)/osp"
      jsonCase: "CamelLower"
      path:     "./"

database:
  default:
    link:  "mysql:root:root@tcp(192.168.1.4:3306)/osp"